version: '3.9'

services:
  kafka1:
    container_name: kafka1
    build: 
      context: .
    environment:
      KAFKA_HEAP_OPTS: "-Xms1024m -Xmx1024m"
    ports:
      - target: 9192
        published: 9192
        protocol: tcp/udp
        mode: host
    networks:
      kafka-net:
        aliases:
          - kafka1
        ipv4_address: 172.21.0.11
    volumes:
    - ./config/kafka1/server.properties:/srv/kafka/broker/config/server.properties
    - kafka1:/srv/kafka/data
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
      restart_policy:
        condition: on-failure
        max_attempts: 1
  kafka2:
    container_name: kafka2
    build: 
      context: .
    environment:
      KAFKA_HEAP_OPTS: "-Xms1024m -Xmx1024m"
    ports:
      - target: 9292
        published: 9292
        protocol: tcp/udp
        mode: host
    networks:
      kafka-net:
        aliases:
          - kafka2
        ipv4_address: 172.21.0.12
    volumes:
    - ./config/kafka2/server.properties:/srv/kafka/broker/config/server.properties
    - kafka2:/srv/kafka/data
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
      restart_policy:
        condition: on-failure
        max_attempts: 1
  kafka3:
    container_name: kafka3
    build: 
      context: .
    environment:
      KAFKA_HEAP_OPTS: "-Xms1024m -Xmx1024m"
    ports:
      - target: 9392
        published: 9392
        protocol: tcp/udp
        mode: host
    networks:
      kafka-net:
        aliases:
          - kafka3
        ipv4_address: 172.21.0.13
    volumes:
    - ./config/kafka3/server.properties:/srv/kafka/broker/config/server.properties
    - kafka3:/srv/kafka/data
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
      restart_policy:
        condition: on-failure
        max_attempts: 1

networks:
  kafka-net:
    ipam:
      config:
        - subnet: 172.21.0.0/16
    # driver: bridge

volumes:
  kafka1:
  kafka2:
  kafka3:
